[package]
name = "beehive_vault_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4.0"
anyhow = "^1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "^0.15.0"
tokio = { version = "1.49.0", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
garde = { version = "0.22.1", features = ["derive", "regex"] }
garde-actix-web = "0.12.0"
actix-cors = "0.7.1"
