[package]
name = "beehive_vault_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4.0"
anyhow = "^1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "^0.15.0"
tokio = { version = "1.49.0", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
garde = { version = "0.22.1", features = ["derive", "regex"] }
garde-actix-web = "0.12.0"
actix-cors = "0.7.1"
actix-governor = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-actix-web = "0.7"
rust_decimal = { version = "1.41", features = ["db-diesel2-postgres", "serde-str"] }
yfinance-rs = { version = "0.7.2", features = ["tracing"] }
tokio-cron-scheduler = "0.15"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt", "macros"] }
