# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["stocks", "metrics_catalog", "metric_values", "score_snapshots", "score_details", "indicator_scores", "indicator_sub_scores", "sector_benchmarks", "portfolios", "transactions"] }

[migrations_directory]
dir = "migrations"
